spring:
  main:
    web-application-type: none
  application:
    name: OpenButler
  ai:
    openai:
      api-key: sk-6754c68e73b1404ebd5b87f5956c6756
      chat:
        options:
          model: qwen3.5-flash
      base-url: https://dashscope.aliyuncs.com/compatible-mode

logging:
  level:
    root: debug
    com.openbutler: debug
    org.springframework.ai.chat.client.advisor: debug
    org.springframework.ai.chat.model.openai: debug
    org.springframework.ai.model.tool: debug
